---
language: bash

before_script:
  - sudo apt-get update
  - sudo apt-get install -y python-software-properties software-properties-common
  - sudo add-apt-repository -y ppa:pi-rho/dev
  - sudo apt-get update
  - sudo apt-get install -y tmux=1.9a-1~ppa1~p
  - tmux new-session -d -s test

script:
  # Basic syntax check
  - bash ./mem.tmux
  - bash ./scripts/mem_percentage.sh
